### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by debarshee2004** [Intellixone-Innovation/Intellixone-Innovation#2]
- [ ] Update the `Readme.md` file
- [ ] Create a folder name `docs` for documentation
- [ ] Create a `Contribution.md` file which explains what to contribute
- [ ] Create a `Todo.md` file for a list of tasks
- [ ] Work on the [main website](https://intellixone.netlify.app/) (written in basic `.html` and `.css` for ease)

**Comment by SunMoon97** [comment]
Hello,

I'm new to the feild of open source contribution and would appreciate some guidance on how to approach this following issue:
I haven't started working on this issue yet, and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!

Best regards,

**Comment by debarshee2004** [comment]
Hello,

I am sorry @SunMoon97, but this is not the best repository to start your open source journey, currently the team which will work on this project has not started working because of exams.

Thank you for your time.

Sincerely,
